CREATE TABLE `user`(
  `id` int NOT NULL AUTO_INCREMENT COMMENT '自增 id',
  `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户名',
  `phone` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '手机号',
  `expire` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '过期时间',
  `chat_balance` INT NOT NULL DEFAULT 0 COMMENT '聊天余额',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_phone` (`phone`) USING BTREE
) ENGINE = InnoDB COMMENT '用户表',
COLLATE = utf8_bin;